### ISSUE TITLE
Support for AGP 3.1.0

### ISSUE THREAD

**Issue by vudzkostek** [kaminomobile/soter#4]
Hi,
Android Studio 3.1.0 was released, along with new AGP. I can see that you've already fixed compatibility issue. But  it seems that version 2.1.2 hasn't been released to mvn yet. When can we see it downloadable? Soter is blocking us at the moment from upgrading to AGP 3.1.0

**Comment by blazsolar** [comment]
Hi,

version 2.1.2 is available in gradle plugin portal (https://plugins.gradle.org/plugin/si.kamino.soter). Let me know if it still doesn't work and i'll take a look.

**Comment by vudzkostek** [comment]
I used configuration from readme (repositories {maven {url "https://plugins.gradle.org/m2/"}} and I got:
 Could not find gradle.plugin.si.kamino.gradle:soter:2.1.2.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/si/kamino/gradle/soter/2.1.2/soter-2.1.2.pom
         https://plugins.gradle.org/m2/gradle/plugin/si/kamino/gradle/soter/2.1.2/soter-2.1.2.jar

Link that you've provided in comment also instructs me to use same repo path.

**Comment by blazsolar** [comment]
strange. I'll look into it.

**Comment by vudzkostek** [comment]
It is weird, because when I will copy link provided by gradle (https://plugins.gradle.org/m2/gradle/plugin/si/kamino/gradle/soter/2.1.2/soter-2.1.2.pom) I also can't find file, but when I change it to 2.1.1 it works. Also I can see that 2.1.2 dir exists and has all necessary files.

**Comment by blazsolar** [comment]
I tried republishing it under `2.1.3`. Can you try it out if ti works. `https://plugins.gradle.org/m2/si/kamino/soter/si.kamino.soter.gradle.plugin/`. Maven repo seams to have both version. So it is strange why it wouldn't work.

**Comment by vudzkostek** [comment]
I still got same issue. I also checked in different project. Adding soter for the first time in version 2.1.3 and 2.1.2 failed as previously stated. But when changed to 2.1.1 it works fine

**Comment by blazsolar** [comment]
Strange, i will have to take a deeper look into this. I'll let you know when i find a solution.

**Comment by vudzkostek** [comment]
When you go to https://plugins.gradle.org/m2/gradle/plugin/si/kamino/gradle/soter/2.1.2/ it will show files, but if you click soter-2.1.2.pom.md5 you will get "Something bad happened. An error (id is: "776a5d") has been logged. Send us a mail if this is our fault" Seems like legit way to check on their side why you've got this problem

**Comment by blazsolar** [comment]
Hi,

i pushed 2.1.4 that fixes issue mentioned above. Can you verify that it works for you.

**Comment by vudzkostek** [comment]
It works fine now. Thank you for help.

**Comment by blazsolar** [comment]
🎆
